#! /bin/sh
### BEGIN INIT INFO
# Provides: raspchat
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: raspchat
# Description: This file starts and stops raspchat server
# 
### END INIT INFO

RASPCHAT_DIR=/root/raspchat

case "$1" in
 start)
   . /$RASPCHAT_DIR/dist/chat-server
   ;;
 stop)
   . /$RASPCHAT_DIR/dist/chat-server
   sleep 10
   ;;
 restart)
   . /$RASPCHAT_DIR/dist/chat-server
   sleep 20
   . /$RASPCHAT_DIR/dist/chat-server
   ;;
 *)
   echo "Usage: raspchat {start|stop|restart}" >&2
   exit 3
   ;;
esac